[project]
name = "report-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "colorama>=0.4.6",
    "discord-py>=2.7.1",
    "matplotlib>=3.10.9",
    "python-dotenv>=1.2.2",
    "supabase>=2.30.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.20",
]
